### ISSUE TITLE
In repl - loadPlugin(ID, clientHandler); throws error

### ISSUE THREAD

**Issue by suleytron** [saikrishna321/taiko-diagnostics#13]
User is in the Taiko REPL:

Using Taiko repl I can require
```const {ID, clientHandler, startTracing, endTracing, getCssCoverage, startCssTracing, stopCssTracing, getPerformanceMetrics, getSpeedIndex } = require('taiko-diagnostics');```
With no issues

But when I reference
```loadPlugin(ID, clientHandler);```

This issue is thrown up:

Thrown:
TypeError: Cannot read property 'exists' of undefined
    at repl.context.(anonymous function) (/Users/username/.nvm/versions/node/v11.10.1/lib/node_modules/taiko/lib/repl.js:190:25)
    at repl:2:9
    at repl:3:3
    at Script.runInContext (vm.js:135:20)
    at Object.defaultEval (repl.js:324:29)
    at bound (domain.js:400:14)
    at Object.runBound (domain.js:413:12)

Result:
This doesn't seem to stop anything from working as I am still able to use all of the diagnostics plugin in the repl. However, something's not quite right

**Comment by saikrishna321** [comment]
@NivedhaSenthil ping

**Comment by NivedhaSenthil** [comment]
This is happening because REPL has a wrapper over every taiko funcs and it expects them to return some result... since loadPlugin has no return value this is happening it has to be handled in taiko REPL. 

On a side note, we may not have to loadPlugin by calling api in REPL, there is a flag to load plugins 
`'--plugin <plugin1,plugin2...>'` I guess documentation has to be updated in Taiko and Taiko diagnostics.

**Comment by suleytron** [comment]
@NivedhaSenthil @saikrishna321 I have tried 

`taiko --plugin '<taiko-diagnostics>'`

 (I use zsh so not sure if you need to use '' in other cmd prompt windows). To load the REPL but it's returning this error. 

`Error: The plugin <taiko-diagnostics> is not installed.
    at loadPlugin (/Users/suley/.nvm/versions/node/v11.10.1/lib/node_modules/taiko/bin/taiko.js:66:30)
    at plugins.split.forEach (/Users/suley/.nvm/versions/node/v11.10.1/lib/node_modules/taiko/bin/taiko.js:78:9)
    at Array.forEach (<anonymous>)
    at loadPlugins (/Users/suley/.nvm/versions/node/v11.10.1/lib/node_modules/taiko/bin/taiko.js:77:24)
    at Command.<anonymous> (/Users/suley/.nvm/versions/node/v11.10.1/lib/node_modules/taiko/node_modules/commander/index.js:412:13)
    at Command.emit (events.js:197:13)
    at Command.parseOptions (/Users/suley/.nvm/versions/node/v11.10.1/lib/node_modules/taiko/node_modules/commander/index.js:733:14)
    at Command.parse (/Users/suley/.nvm/versions/node/v11.10.1/lib/node_modules/taiko/node_modules/commander/index.js:471:21)
    at Object.<anonymous> (/Users/suley/.nvm/versions/node/v11.10.1/lib/node_modules/taiko/bin/taiko.js:119:13)
    at Module._compile (internal/modules/cjs/loader.js:738:30)`

I have already installed taiko-diagnostics. So not sure what is going on, do you have any ideas? When this is sorted I will do a pr for updating taiko-diagnostics documents to match your approach

**Comment by saikrishna321** [comment]
@suleytron right way to use is `taiko --plugin taiko-diagnostics`

**Comment by saikrishna321** [comment]
Closing as fix has been merged to Taiko master.
