### ISSUE TITLE
Not Able to get speedIndex and performance parameters using latest taiko-diagnostic 

### ISSUE THREAD

**Issue by vikasg52** [saikrishna321/taiko-diagnostics#275]
======================================================================================
Getting this error message:
======================================================================================
TypeError: Cannot read property 'traceEvents' of undefined
    at Function.compute (/Users/vikasgarg/Documents/Automation/btest/node_modules/taiko-diagnostics/lib/lighthouse/tabTracing.js:78:59)
    at TracingHandler.getPerformanceMetrics (/Users/vikasgarg/Documents/Automation/btest/node_modules/taiko-diagnostics/lib/tracingHandler.js:71:40)
TypeError: Cannot read property 'traceEvents' of undefined
    at Object.extractFramesFromTimeline (/Users/vikasgarg/Documents/Automation/btest/node_modules/speedline/core/lib/frame.js:112:21)
    at module.exports (/Users/vikasgarg/Documents/Automation/btest/node_modules/speedline/core/lib/index.js:55:15)
    at TracingHandler.getSpeedIndex (/Users/vikasgarg/Documents/Automation/btest/node_modules/taiko-diagnostics/lib/tracingHandler.js:63:38)
TypeError: Cannot read property 'traceEvents' of undefined
    at Object.extractFramesFromTimeline (/Users/vikasgarg/Documents/Automation/btest/node_modules/speedline/core/lib/frame.js:112:21)
    at module.exports (/Users/vikasgarg/Documents/Automation/btest/node_modules/speedline/core/lib/index.js:55:15)
    at TracingHandler.getSpeedIndex (/Users/vikasgarg/Documents/Automation/btest/node_modules/taiko-diagnostics/lib/tracingHandler.js:63:38)

**Comment by saikrishna321** [comment]
Please post the code snippet you have tried?

**Comment by vikasg52** [comment]
@saikrishna321 : Here is the code snippet:
--------------------------------------------------------------------------------------------------
const diagnostics = require('taiko-diagnostics');
const assert = require('assert').strict;
const { openBrowser, goto, click, textBox, into, write, $, title, closeBrowser, currentURL } = require('taiko');
const {
  startTracing,
  startCssTracing,
  stopCssTracing,
  endTracing,
  getSpeedIndex,
  getPerformanceMetrics 
} = diagnostics;
 
 (async () => {
    try {
        await openBrowser({args:['--window-size=1440,900']});
        await goto('URL');
await startTracing();   
        await click('Mantener ubicación');
        await click('Li cuenta');
        await write("email", into(textBox({id: "inputEmail"})));
        await write("password", into(textBox({id: "loginPassword"})));
        await click($("//*[@id='newProcessLogin']"));
 await endTracing();
        console.log(getSpeedIndex());
        await getPerformanceMetrics();
        await click('Hola');
        await click($("//li[contains(@id,'myPurchaseLink')]"));
        assert.ok(await text('Todos los').exists());
        assert.ok(await text('Ver detalles').exists());
       
        console.log(getPerformanceMetrics());     
        await click('Cerrar sesión');
        if (assert.strictEqual(await currentURL(), 'url',"CURRENT URL IS WRONG")==true){
        console.log("Logout is success");
        }
        

} catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
-------------------------------------------------------------------------------------------------------------------------
Output:
![image](https://user-images.githubusercontent.com/8328086/95000892-71819e80-05e2-11eb-9c27-85c6910514b0.png)

**Comment by saikrishna321** [comment]
@vikasg52 I see browser has crashed. 

>> Connection to browser lost

Without the diagnostics plugin does the same test work fine.

**Comment by vikasg52** [comment]
@saikrishna321 - I tried again and this time browser is not crashing: Why I am getting the promise error? Also I wanted to see the speed index numbers - Those are not printed in the logs.

![image](https://user-images.githubusercontent.com/8328086/95048942-66c02a00-0706-11eb-9b49-d3c1e54835f7.png)

**Comment by saikrishna321** [comment]
You need to resolve the promise. You are missing await in the console.log

**Comment by vikasg52** [comment]
@saikrishna321 -Promise error resolved. But I am getting below mentioned error:
![image](https://user-images.githubusercontent.com/8328086/95117551-65264e80-0766-11eb-9134-8a161012c697.png)

**Comment by saikrishna321** [comment]
https://github.com/getgauge/taiko/issues/533
